"""
Utility functions for MedInsight AI - RadiologyAI Pro
"""
import streamlit as st
from PIL import Image
import google.generativeai as genai
import io
from datetime import datetime
from reportlab.lib.pagesizes import letter, A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image as RLImage, PageBreak
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.lib.colors import HexColor
import tempfile

def process_image(uploaded_file):
    """Convert uploaded file to PIL Image"""
    try:
        image = Image.open(uploaded_file)
        return image
    except Exception as e:
        st.error(f"❌ Error processing image: {str(e)}")
        return None

def generate_report(image, prompt):
    """Generate report using Gemini API"""
    try:
        # Configure the model (assuming GEMINI_API_KEY is available in environment)
        model = genai.GenerativeModel('gemini-2.0-flash-exp')
        
        with st.spinner("🔄 Analyzing image and generating report..."):
            response = model.generate_content([prompt, image])
            return response.text
    except Exception as e:
        st.error(f"❌ Error generating report: {str(e)}")
        return None

def create_pdf_report(report_text, image, report_type, patient_info=None):
    """Create a PDF report with the analysis results"""
    try:
        # Create a temporary file
        temp_file = tempfile.NamedTemporaryFile(delete=False, suffix='.pdf')
        
        # Create PDF document
        doc = SimpleDocTemplate(temp_file.name, pagesize=A4)
        story = []
        styles = getSampleStyleSheet()
        
        # Custom styles
        title_style = ParagraphStyle(
            'CustomTitle',
            parent=styles['Heading1'],
            fontSize=24,
            textColor=HexColor('#1e3a8a'),
            spaceAfter=30,
            alignment=TA_CENTER,
            fontName='Helvetica-Bold'
        )
        
        heading_style = ParagraphStyle(
            'CustomHeading',
            parent=styles['Heading2'],
            fontSize=16,
            textColor=HexColor('#667eea'),
            spaceAfter=12,
            spaceBefore=12,
            fontName='Helvetica-Bold'
        )
        
        # Title
        story.append(Paragraph("🏥 MEDICAL IMAGING ANALYSIS REPORT", title_style))
        story.append(Spacer(1, 0.3*inch))
        
        # Report Information
        story.append(Paragraph(f"<b>Report Type:</b> {report_type}", styles['Normal']))
        story.append(Paragraph(f"<b>Date Generated:</b> {datetime.now().strftime('%B %d, %Y at %I:%M %p')}", styles['Normal']))
        story.append(Spacer(1, 0.2*inch))
        
        # Add patient info if provided
        if patient_info:
            story.append(Paragraph("PATIENT INFORMATION", heading_style))
            for key, value in patient_info.items():
                story.append(Paragraph(f"<b>{key}:</b> {value}", styles['Normal']))
            story.append(Spacer(1, 0.2*inch))
        
        # Add image if available
        if image:
            try:
                # Save image temporarily
                img_temp = tempfile.NamedTemporaryFile(delete=False, suffix='.png')
                image.save(img_temp.name, format='PNG')
                
                # Add image to PDF
                story.append(Paragraph("ANALYZED IMAGE", heading_style))
                img = RLImage(img_temp.name, width=4*inch, height=3*inch)
                story.append(img)
                story.append(Spacer(1, 0.3*inch))
            except Exception as e:
                print(f"Could not add image to PDF: {e}")
        
        # Add report content
        story.append(Paragraph("ANALYSIS REPORT", heading_style))
        story.append(Spacer(1, 0.1*inch))
        
        # Process report text
        for line in report_text.split('\n'):
            if line.strip():
                if line.startswith('#'):
                    story.append(Paragraph(line.replace('#', '').strip(), heading_style))
                else:
                    story.append(Paragraph(line, styles['Normal']))
                story.append(Spacer(1, 0.1*inch))
        
        # Disclaimer
        story.append(Spacer(1, 0.3*inch))
        disclaimer_style = ParagraphStyle(
            'Disclaimer',
            parent=styles['Normal'],
            fontSize=10,
            textColor=HexColor('#dc2626'),
            borderColor=HexColor('#dc2626'),
            borderWidth=1,
            borderPadding=10,
            backColor=HexColor('#fef2f2')
        )
        story.append(Paragraph(
            "<b>⚠️ IMPORTANT DISCLAIMER:</b> This report is generated by AI and is for preliminary analysis only. "
            "All findings must be reviewed and validated by a qualified healthcare professional before making "
            "any clinical decisions.",
            disclaimer_style
        ))
        
        # Build PDF
        doc.build(story)
        
        # Read the PDF file
        with open(temp_file.name, 'rb') as f:
            pdf_data = f.read()
        
        return pdf_data
    
    except Exception as e:
        st.error(f"❌ Error creating PDF: {str(e)}")
        return None